# Generated by Django 6.1 on 2026-08-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('heart_disease', 'Heart Disease'), ('diabetes', 'Diabetes'), ('kidney_disease', 'Chronic Kidney Disease'), ('breast_cancer', 'Breast Cancer'), ('liver_disease', 'Liver Disease')], max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
